name: HTML5

on: [workflow_dispatch]

jobs:
  build:
    name: Build and Deploy for ${{matrix.target}}
    strategy:
      matrix:
        include: 
          - os: windows-latest
            target: html5
            channel: html5
            folder: html5
            butler: windows-amd64
#           - os: windows-latest
#             target: windows
#             channel: windows
#             folder: windows
#             butler: windows-amd64
#           - os: macos-latest
#             target: mac
#             channel: mac
#             folder: macos
#             butler: darwin-amd64
         # - os: ubuntu-latest
         #   target: linux
         #   channel: linux
         #   folder: linux
         #   butler: linux-amd64
                       
    runs-on: ${{matrix.os}}
    
    steps:
      - uses: krdlab/setup-haxe@v1
        with:
          haxe-version: 4.1.5
      - uses: actions/checkout@v2.3.4
      - uses: actions/checkout@v2
        with:
          repository: axolstudio/axollib
          path: axollib
          token: ${{secrets.PAT}}
      - run: haxelib install lime 7.8.0 --quiet
      - run: haxelib install openfl 9.0.2 --quiet
      - run: haxelib install flixel 4.8.1 --quiet
      - run: haxelib install flixel-addons 2.9.0 --quiet
      - run: haxelib install flixel-ui 2.3.3 --quiet
      - run: haxelib dev axollib axollib --quiet
      - run: haxelib install hxcpp 4.1.15 --quiet
      - run: haxelib install hscript 2.4.0 --quiet
      - run: haxelib install sure 0.1.1 --quiet
      - run: haxelib run lime build ${{matrix.target}} -clean -nolaunch
      - run: curl -L -o butler.zip "https://broth.itch.ovh/butler/${{matrix.butler}}/LATEST/archive/default"
      - run: unzip butler.zip
      - run: chmod +x butler
      - run: ./butler -V
      - env:
          BUTLER_API_KEY: ${{ secrets.BUTLER_CREDENTIALS }}
        run: ./butler push export/${{matrix.folder}}/bin axolstudio/monster-match:${{matrix.channel}} --if-changed
